# Generated by Django 4.1.1 on 2022-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0002_coustom_users_delete_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustom_users',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
