# Generated by Django 4.1.1 on 2022-10-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0004_remove_coustom_users_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coustom_Users',
        ),
    ]
