# Generated by Django 4.1.1 on 2022-10-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0007_alter_profile_no_test_taken_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
