# Generated by Django 4.1.1 on 2022-10-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0011_alter_profile_no_test_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Free', models.BooleanField(default=True)),
                ('Date_created', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionpaper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roughPhilaquest.questionpaper')),
                ('questNo', models.PositiveSmallIntegerField()),
                ('ques_tion', models.CharField(max_length=3000)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('CorrectOption', models.TextField(choices=[('Opt1', 'option1'), ('Opt2', 'option2'), ('Opt3', 'option3'), ('Opt4', 'option4')])),
                ('Ques_image', models.ImageField(null=True, upload_to='Question/img')),
            ],
            bases=('roughPhilaquest.questionpaper',),
        ),
    ]
