# Generated by Django 4.1.1 on 2022-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0013_alter_questionpaper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Ques_image',
            field=models.ImageField(blank=True, upload_to='Question/img'),
        ),
    ]
