# Generated by Django 4.1.1 on 2022-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0016_alter_questions_ques_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='response_test1',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
