# Generated by Django 4.1.1 on 2022-10-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0017_alter_profile_response_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Test1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Test2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Test3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Test4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Test5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Test6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Test7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_test2',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_test3',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_test4',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_test5',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_test6',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_test7',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
