# Generated by Django 4.1.1 on 2022-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0019_profile_profilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='DisplayName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
