# Generated by Django 4.1.1 on 2022-10-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughPhilaquest', '0020_questionpaper_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='No_Test_Taken',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
